# Generated by Django 5.1.1 on 2024-10-01 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='pago_realizado',
        ),
        migrations.AddField(
            model_name='pagos',
            name='fecha_pago_realizado',
            field=models.DateField(default="2001-10-10"),
            preserve_default=False,
        ),
    ]
