# Generated by Django 5.1.1 on 2024-10-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_remove_pagos_pago_realizado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago_realizado',
            field=models.DateField(blank=True, null=True),
        ),
    ]
