# Generated by Django 5.1.1 on 2024-10-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pagos_fecha_pago_realizado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='monto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
