# Generated by Django 5.1.1 on 2024-10-05 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_inscripcion_horario_fin_inscripcion_horario_inicio'),
        ('miembros', '0007_visitantes_asistencias_visitantes_clase_and_more'),
        ('pagos', '0004_alter_pagos_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos',
            name='visitante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miembros.visitantes'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='inscripcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inscripciones.inscripcion'),
        ),
        migrations.AlterField(
            model_name='pagos',
            name='miembro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='miembros.miembro'),
        ),
    ]
