# Generated by Django 5.1.1 on 2024-10-01 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='roles',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
