# Generated by Django 5.1.1 on 2024-10-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_customuser_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='num_control',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
