# Generated by Django 5.1.1 on 2024-09-30 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('num_control', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('tipo_sangre', models.CharField(max_length=3)),
                ('facebook', models.TextField(blank=True, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('nss', models.CharField(max_length=11, unique=True)),
                ('dependencia', models.CharField(max_length=100)),
                ('telefono_fijo', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('hijos', models.IntegerField(blank=True, null=True)),
                ('edades', models.CharField(blank=True, max_length=100, null=True)),
                ('padre_tutor', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_tutor', models.CharField(blank=True, max_length=15, null=True)),
                ('contacto_emergencia', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='HistorialDeportivo',
            fields=[
                ('miembro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='miembros.miembro')),
                ('deporte_actual', models.CharField(blank=True, max_length=255, null=True)),
                ('actividad_fisica_reciente', models.JSONField(blank=True, null=True)),
                ('lesion', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('miembro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='miembros.miembro')),
                ('padecimientos', models.TextField(blank=True, null=True)),
                ('medicamentos', models.TextField(blank=True, null=True)),
                ('descripcion_accidente', models.TextField(blank=True, null=True)),
                ('descripcion_operacion', models.TextField(blank=True, null=True)),
                ('descripcion_hospitalizacion', models.TextField(blank=True, null=True)),
                ('desmayos_ejercicio', models.BooleanField(blank=True, null=True)),
                ('traumatismo_oseo', models.JSONField(blank=True, null=True)),
                ('golpe_cabeza', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedad_actual', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
