# Generated by Django 5.1.1 on 2024-10-01 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='alergias',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='medicamentos',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialmedico',
            name='padecimientos',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
