# Generated by Django 5.1.1 on 2024-10-01 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0002_alter_historialmedico_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='num_control',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
