# Generated by Django 5.1.1 on 2024-10-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0005_visitantes'),
    ]

    operations = [
        migrations.AddField(
            model_name='miembro',
            name='estado_civil',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='dependencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nss',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='tipo_sangre',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
