# Generated by Django 5.1.1 on 2024-10-04 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0006_miembro_estado_civil_alter_miembro_dependencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantes',
            name='asistencias',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='clase',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visitantes',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitantes',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
