# Generated by Django 5.1.1 on 2024-10-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0007_visitantes_asistencias_visitantes_clase_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='miembro',
            old_name='apellidos',
            new_name='materno',
        ),
        migrations.AddField(
            model_name='miembro',
            name='paterno',
            field=models.CharField(default='Ejemplo', max_length=100),
            preserve_default=False,
        ),
    ]
