# Generated by Django 5.1.1 on 2024-10-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0008_rename_apellidos_miembro_materno_miembro_paterno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visitantes',
            old_name='apellidos',
            new_name='materno',
        ),
        migrations.AddField(
            model_name='visitantes',
            name='paterno',
            field=models.CharField(default='Ejemplo', max_length=100),
            preserve_default=False,
        ),
    ]
