# Generated by Django 5.1.1 on 2024-10-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0009_rename_apellidos_visitantes_materno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='asistencias',
            field=models.IntegerField(default=1),
        ),
    ]
