# Generated by Django 5.1.1 on 2024-10-05 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0010_alter_visitantes_asistencias'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitantes',
            name='ultima_visita',
            field=models.DateField(default="2024-10-11"),
            preserve_default=False,
        ),
    ]
