# Generated by Django 5.1.1 on 2024-10-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0011_visitantes_ultima_visita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='alergias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
