# Generated by Django 5.1.1 on 2024-10-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0012_alter_historialmedico_alergias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
