# Generated by Django 5.1.1 on 2024-10-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0013_alter_miembro_celular_alter_miembro_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='alergias',
            field=models.TextField(blank=True, default='Ninguna', null=True),
        ),
    ]
