# Generated by Django 5.1.1 on 2024-10-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0014_alter_historialmedico_alergias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitantes',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
