# Generated by Django 5.1.1 on 2024-10-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0015_alter_visitantes_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='miembro',
            name='dependencia',
            field=models.CharField(blank=True, default='Ninguna', max_length=100, null=True),
        ),
    ]
