# Generated by Django 5.1.1 on 2024-10-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0016_alter_miembro_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='alergias',
            field=models.TextField(default='Ninguna'),
        ),
    ]
