# Generated by Django 5.1.1 on 2024-10-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miembros', '0017_alter_historialmedico_alergias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialmedico',
            name='alergias',
            field=models.TextField(blank=True, default='Ninguna', null=True),
        ),
    ]
