# Generated by Django 5.1.1 on 2024-10-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
    ]
