# Generated by Django 5.1.1 on 2024-10-06 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
