# Generated by Django 5.1.1 on 2024-10-01 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gimnasiaartistica',
            name='modalidad',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='gimnasiomixto',
            name='modalidad',
            field=models.CharField(max_length=50),
        ),
    ]
