# Generated by Django 5.1.1 on 2024-10-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_alter_gimnasiaartistica_modalidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscripcion',
            name='gimnasia_artistica',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='gimnasio_mixto',
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='clase',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='modalidad',
            field=models.CharField(default='Semanal', max_length=50),
            preserve_default=False,
        ),
    ]
