# Generated by Django 5.1.1 on 2024-10-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0004_rename_monto_inscripcion_costo'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='horario_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='horario_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
