# Generated by Django 5.1.1 on 2024-10-11 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0005_inscripcion_horario_fin_inscripcion_horario_inicio'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroPeticion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
    ]
